services:
  auth-db:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - auth-db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - auth-network

  auth-host:
    container_name: auth.service
    build:
      context: .
      dockerfile: Auth.Host/Dockerfile
    env_file:
      - .env
    depends_on:
      - auth-db
    ports:
      - "8080:8080"
    volumes:
      - auth-keys:/app/keys
    networks:
      - auth-network

volumes:
  auth-db-data:
  auth-keys:

networks:
  auth-network:
    driver: bridge
    name: auth-network
