services:
  auth-db:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - auth-db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - auth-network

  auth-host:
    container_name: auth.service
    build:
      context: .
      dockerfile: Auth.Host/Dockerfile
    env_file:
      - .env
    depends_on:
      - auth-db
    ports:
      - "8080:8080"
    networks:
      - auth-network

  auth-web:
    container_name: auth.web
    build:
      context: Auth.Web
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      - auth-host
    ports:
      - "127.0.0.1:4173:4173"
    networks:
      - auth-network

volumes:
  auth-db-data:

networks:
  auth-network:
    driver: bridge
    name: auth-network
