services:
  auth-host:
    container_name: auth.service
    build:
      context: .
      dockerfile: Auth.Host/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - auth-keys:/app/keys
    networks:
      - auth-network
      - nginx_network

volumes:
  auth-db-data:
  auth-keys:

networks:
  auth-network:
    driver: bridge
    name: auth-network

  nginx_network:
    external: true
    driver: driver
